name: cse6250-project
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - blosc=1.21.3
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.5
  - ca-certificates=2023.08.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - hdf5=1.12.1
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.5.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libcurl=8.4.0
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - numexpr=2.8.7
  - numpy-base=1.26.0
  - openssl=3.0.12
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.40
  - prompt_toolkit=3.0.40
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pygments=2.16.1
  - pytables=3.8.0
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.13.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.9
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - annotated-types==0.6.0
      - astunparse==1.6.3
      - blis==0.7.11
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.3
      - cymem==2.0.8
      - en-core-med7-lg==3.4.2.1
      - flatbuffers==23.5.26
      - gast==0.4.0
      - gensim==4.3.2
      - glove-python3==0.1.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - h5py==3.10.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - jax==0.4.20
      - jinja2==3.1.2
      - joblib==1.3.2
      - keras==2.14.0
      - langcodes==3.3.0
      - libclang==16.0.6
      - llvmlite==0.41.1
      - markdown==3.5.1
      - markupsafe==2.1.3
      - ml-dtypes==0.2.0
      - murmurhash==1.0.10
      - nltk==3.8.1
      - np-utils==0.6.0
      - numba==0.58.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.16.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==2.1.3
      - pathy==0.10.3
      - preshed==3.0.9
      - protobuf==4.25.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.13
      - pydantic-core==2.10.1
      - pytz==2023.3.post1
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - smart-open==6.4.0
      - spacy==3.4.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorrt==8.5.3.1
      - termcolor==2.3.0
      - thinc==8.1.12
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - typer==0.7.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - wasabi==0.10.1
      - weasel==0.3.4
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - zipp==3.17.0
